### ISSUE TITLE
!8ball can be used to ping people

### ISSUE THREAD

**Issue by Tomoli75** [RedstoneDaedalus/verifybot#49]
As well as the message deletion (looks like a ghost ping), VerifyBot can ping anyone and so this can be used to ping @Support etc.

**Comment by SiebeDW** [comment]
#55 should fix this.

**Comment by LittleWhole** [comment]
@RedstoneDaedalus close this issue.

**Comment by Tomoli75** [comment]
Closing as #55 fixes
